### ISSUE TITLE
Wrong userid and chmod -R

### ISSUE THREAD

**Issue by ghost** [jessfraz/irssi#17]
Something doesn't seem right. First time trying irssi via docker (latest `irssi:alpine`). Very cool, but...

A simple /save after irssi starts up gives you this.

`Error: Couldn't save configuration file: Permission denied`
`00:59 -!- Irssi: Error saving theme to /home/user/.irssi/default.theme: Permission denied`

Had a look at the Dockerfile for this and noticed I should be user `user` with uid 1001 and the `.irssi` directory should be created and writable since the `chmod -R` was run.

`RUN adduser -u 1001 -D user \`
`&& mkdir -p $HOME/.irssi \`
`&& chown -R user:user $HOME`

But that doesn't seem to be the case for some reason. I started my container like this.

`docker run --rm -it --name my-running-irssi -e TERM -u $(id -u):$(id -g)     --log-driver=none     -v $HOME/.irssi:/home/user/.irssi     -v /etc/localtime:/etc/localtime:ro irssi:alpine`

Notice I removed the trailing `:ro` from the .irssi volume part.

So `/home/user/.irssi` should be writable. Ran it again and turned logging on. Got this...

`(irssi:1): GLib-WARNING **: getpwuid_r(): failed due to unknown user id (1000)`
`NO WINDOWS: -!- Irssi: Transliterations not supported in this system`

So for whatever reason, I'm not in the container as uid 1001 (`user`), but uid 1000.

Overrode the CMD to `/bin/sh` and had a poke around.

```
/home/user $ pwd
/home/user
/home/user $ ls -la
total 12
drwxr-sr-x    3 user     user          4096 Jul 13 16:40 .
drwxr-xr-x    3 root     root          4096 Jul 13 16:40 ..
drwxr-xr-x    2 root     root          4096 Jul 22 00:36 .irssi
/home/user $ # Hmm... while I'm not user (1001) and 1000 instead,
/home/user $ # why is .irssi still owned by root?
```

My docker version (old, but still)...

```
$ docker --version
Docker version 1.7.1, build 786b29d/1.7.1
```
I tired to add the -u 0 and -u 1001 options to get it to run as the right user (or as root so I could poke around), but I don't think my docker skills are aged enough.

**Comment by tianon** [comment]
It's because of `-v $HOME/.irssi:/home/user/.irssi` -- `$HOME/.irssi` on your host didn't exist, so Docker created it, and it's thus now owned by root.

What I'd recommend doing is `sudo rm -rf "$HOME/.irssi"`, then as your user doing `mkdir "$HOME/.irssi"`.  Once you do that, irssi in the container (with the `-u` you've specified) should work and be able to write to it appropriately.

**Comment by ghost** [comment]
Ahhhh! Of course. I'm dealing with a container managed by a daemon running as root. Makes perfect sense I guess. My `.irssi` directory is on my *real* machine and not this test rig, so it had to make one. I get it.

It works now and I think my uid 1000 vs 1001 _finding_ was a red herring. It seems to be working correctly. I'm quite new to docker so I think I may have been tripped with running the image with `/bin/ash` as the CMD and setting `-u` to something. `whoami` always returns with uid 1000. If I do it on the regular alpine image, it seems to work. But whatever... thank you.
