### ISSUE TITLE
VOLUME instruction causes permissions havoc when consuming this image

### ISSUE THREAD

**Issue by hairyhenderson** [jessfraz/irssi#2]
So, let's say I want to package up my own irssi config:

``` Dockerfile
FROM irssi

COPY config $HOME/.irssi/

# attempt to change ownership of config file (and everything else)
USER root
RUN chown -R user.user $HOME
USER user
```

The config file will be owned by root, and if I try to counter that with a `chown`, it (surprisingly) doesn't get re-owned by `user`. This is because the `irssi` image has a `VOLUME $HOME/.irssi` instruction...

Is the `VOLUME` instruction really that useful in this image? Maybe it could be removed?

**Comment by tianon** [comment]
Fixed by https://github.com/jessfraz/irssi/pull/13 :+1: :innocent:
